version: "3.9"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/
      - ./nginx/certbot/www:/var/www/certbot/
      - ./nginx/certbot/conf/:/etc/nginx/ssl/
      - static_volume:/code/staticfiles
      - ./log/nginx:/var/log/nginx
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./nginx/certbot/www/:/var/www/certbot/:rw
      - ./nginx/certbot/conf/:/etc/letsencrypt/:rw
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web: &web
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DEBUG=False
    depends_on:
      - db
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - ./mediafile:/code/mediafile
volumes:
  postgres_data:
  static_volume: